### ISSUE TITLE
Add Quickstart to Docs

### ISSUE THREAD

**Issue by sprjr** [jmeas/resourceful-redux#113]
Just started putting this into one of my apps, and the guides look really good - but also they seem _exhaustive_ from first glance. The intro & guides contain a lot of information, which I do need to read anyway, but it felt like I was reading more about what a resource *is* instead of *how to use this in my app*.

Is it possible we could add a snippet to the `README` and the docs that are just like "here are the 2 things you need to do to get started with the simplest examples"?

**Comment by jmeas** [comment]
Great idea. I'll add this soon.
