### ISSUE TITLE
Invalid data ingest caused some weird results in the store

### ISSUE THREAD

**Issue by sprjr** [jmeas/resourceful-redux#118]
Earlier today I was wiring up to an API and the response looked something like this:

```
[
  {
    myId: 1234,
    foo: 'bar'
  }
]
```

I of course saw a warning that `id` needs to be used, but I noticed that some of the label/meta ingest operations still proceeded and I don't think they updated the store slice in a meaningful way:

<img width="1433" alt="slice-update" src="https://user-images.githubusercontent.com/682566/28094695-04e6ce30-6653-11e7-8da7-d9a69d1a6c21.png">

We should probably abort those operations when we receive invalid objects if we're not allowing it, right?

**Comment by jmeas** [comment]
Definitely. Thanks for the issue, I'll fix this soon!

**Comment by jmeas** [comment]
As a separate issue, it looks like the label you used was super borked. I'll add a warning for ensuring that labels are strings.
