### ISSUE TITLE
CJS Module Issue

### ISSUE THREAD

**Issue by sprjr** [jmeas/resourceful-redux#179]
Debugging some build stuff in my app, we ended up realizing that the `dist/*` files have a small bug for the uglify/envify checks in Resourceful.

```
if ("development" !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
  warning('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Resourceful Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
}
```

After chatting with @jmeas we think this is because I'm not on Webpack 2.0 so it's not using the `es/*` files when its bundling, which is why we're seeing warnings even though the NODE_ENV variable is correctly set.

**Comment by jmeas** [comment]
Thanks for the report, @sprjr ! It turns out this bug also affects Redux itself. I opened an issue here: https://github.com/reactjs/redux/issues/2558

I'll do a bug fix release soon.
