### ISSUE TITLE
Rename "NULL" status to "NIL"/“NONE”/“BLANK”/something else

### ISSUE THREAD

**Issue by jmeas** [jmeas/resourceful-redux#18]
That way, I can use `none` as the return value from `getStatus` (`null` _works_, but it's confusing, and may not work in some older browsers). Also "none" seems like it'd be read out loud as "no status," which seems more logical than "null status."

Unfortunately "DELETE_RESOURCES_NONE" doesn't sound so good.

**Comment by jmeas** [comment]
//cc @sprjr

**Comment by sprjr** [comment]
None sounds pretty good too! Did we cover that in slack already?

**Comment by jmeas** [comment]
Yeah, that's what started it all. `READ_RESOURCES_NONE` doesn't sound very good, which is why I went looking for another option.

**Comment by sprjr** [comment]
Oh right. I'm the worst at email GitHub. Still leaning toward `blank` or clear

**Comment by jmeas** [comment]
@ericvaladas suggested `nil`, which I think is a good option.

So far I think VOID/NULL are my favorites, but can’t be used due to the fact that they’re JS keywords.

NONE is runner up, but `READ_RESOURCES_NONE` just sounds pretty bad.

NIL/BLANK are next. I think I prefer nil over blank, although I don’t think the JS community uses the word nil very often (if ever? :P )

**Comment by jmeas** [comment]
Gonna leave it as null for now. Feel free to comment if you think it should be changed!
