### ISSUE TITLE
Action Creators Update - XHR Callback

### ISSUE THREAD

**Issue by sprjr** [jmeas/resourceful-redux#180]
Mucking around again with a UI issue I ran into. I have been doing post-success side effects in `componentDidUpdate` as my current flow for a given UI is something like

1. Get Resource A
1.1 Get Resource B
1.2 Get Resource A additional data

I was chatting with @jmeas and @marlonpp about this, and we think it might be a good idea to find a way to support a `callback` similar to how XHR does.

There are a few ways we could do this, of course, and some things we could do to pass control of dispatching after the fact back to users. I don't have a use case for this myself, but I do have a use case for some kind of 'perfom non-transform side effects after XHR completion'. That could look like:

```
readResources({
  label,
  resourceName: 'resourceA',
  xhrOptions,
}, (err, res, body) => {
  const resources = body;
  getResourceB(resources.map(resource => resource.b_relationship_id);
  getResourceAExtras(resources.map(resource => resource.id);

  return;
});
```

Right now, it's not actually possible for passing `xhrOptions.callback` as this gets overridden by action creators. So we may want to document that, or _allow_ support for this feature via that prop. It's also possible we could support both that option property and the second argument - but I'm not sure which of the 3 options is better.

Another consideration is, do we _also_ want to give control of dispatches back to the post-XHR callback? That could be useful as well - and initially James said that could maybe be a `dispatchResolver` function provided to the call back that would allow you to invoke the dispatch on your own terms.

Thoughts?

/cc @vinodkl @tbranyen

**Comment by jmeas** [comment]
Resolved in #181
