### ISSUE TITLE
404 metadata?

### ISSUE THREAD

**Issue by jmeas** [jmeas/resourceful-redux#83]
A 404 response for a resource is pretty common. Right now, this lib makes no distinction between general-purpose errors, and not found errors. In other words, all you have to work with is a `failed` boolean, so any error message you display would just be: "There was an error fetching this resource."

It might make sense to include something to handle this in the library, rather than make a plugin. I'm thinking it'd work like this:

```
{
  notFound: Boolean
}
```

`false` by default, and `true` whenever a 404 error is returned. Applies to resources as well as labels.

Note that this would require enforcing a standard format for errors, since the reducer would need access to the status code of the response (right now, it doesn't look at those ever). This might be one reason to make it a plugin instead. It could just be a formal plugin (i.e.; `resourceful-plugins` on npm).

This also makes me think we need a `getMeta` method, which resolves a path to a meta location, so that you can access this meta more easily.

What do y'all think, @tbranyen @sprjr @marlonpp @ericvaladas ?

**Comment by marlonpp** [comment]
+1 for the plugin. It could contain more than just 404, but 401 and 403.

**Comment by sprjr** [comment]
I don't know, I like that this lib tracks the current status of any given resource (i.e. in flight, failed, etc). I think this is putting more potential 'user-land' code in the lib than necessary? Maybe not.

I personally would rather just know that something failed, and be given that failure somehow so I can take care of it how I need to in app land any how. I don't see a huge advantage between that and `.notFound` currently - as either way I have to "interpret some status, and then do something about that".

Seems like error normalization is a stretch, and could cause headaches for the lib.

**Comment by jmeas** [comment]
Alright, I agree with you both. I'll make it a plugin, rather than in core!

**Comment by jmeas** [comment]
Closing in favor of #83
