### ISSUE TITLE
resourceful-plugins

### ISSUE THREAD

**Issue by jmeas** [jmeas/resourceful-redux#89]
This will be a new lib that has some useful plugins for people to use alongside resourceful.

- [x] `httpStatusCodes` plugin (and possibly a plugin for unauthorized, too) #83
- [x] `selection` plugin (the example from the plugins guide)
- [x] `reset` plugin #17
- [ ] `httpNetworkErrors` plugin
- [ ] `attributeUpdates` plugin - per-attribute metadata tracking

Possibly others?

**Comment by marlonpp** [comment]
`normalize` plugin - create a map from resource array?

**Comment by jmeas** [comment]
Interesting idea, @marlonpp ! Can you provide more info about how that would be used? Maybe a little code snippet?

**Comment by jmeas** [comment]
I spoke with @marlonpp about the `normalize` plugin. Now that resources are stored in an object, we should be good to go there, so we don't think any action is needed.

He brought up another good idea, which is failed requests due to timeouts or network errors. This will potentially be different depending on which tool the dev uses for making http requests, but I can _at least_ make a version that works with the Resourceful Action Creators lib.

**Comment by jmeas** [comment]
Gonna close this as resolved, even though there are 2 plugins still listed. The per-attribute tracking will be part of a JSON API extension ( #38 ), and the network errors plugin will require some pretty thorough research into how network errors are reported in various tools.
